# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159da45154170cf26e83b9db97256434983b7a61e1bad05b2f4c63d4675f32452ff08beb0670285d3c0d3d21b58d76485376da8c08326c9d6443a1dbf100278d

test:
  secret_key_base: 82a8b4de9c7ad5c7fb16701fc9f7dd9932ca0c1b05a81ef455005bae40c34907f0873d5b15e4a819a7ebd2ba2b45383080f18e2a970a3ce70981691eb6b58df6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f5ccdd79d3bced178675318c0d4e65e4bfe597ff20609942280c80d2f17779a15c4fdea1e972c052d3ec441d762fac1606c64677d0cbe3a1050b6bc0ca6f74dd
